services:
  salary:
    container_name: salary
    build:
      context: ./
      dockerfile: ./salary/Dockerfile
    env_file:
      - .env
    command:
      aiogram run polling src.api.bot.main:dp --token ${BOT_TOKEN}

  mongo:
    image: mongo:7-jammy
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo:/data/db
      - mongo-config:/data/configdb
    restart: always

volumes:
  mongo:
  mongo-config: